const PDFDocument = require('pdfkit');
const Property = require('../models/Property');
const path = require('path');
const fs = require('fs');
const https = require('https');

exports.generateBrochure = async (req, res) => {
    try {
        const property = await Property.findById(req.params.id);
        if (!property) {
            return res.status(404).json({ message: "Property not found" });
        }

        const doc = new PDFDocument();
        const filename = `Brochure-${property.title.replace(/[^a-z0-9]/gi, '_')}.pdf`;

        res.setHeader('Content-disposition', `attachment; filename="${filename}"`);
        res.setHeader('Content-type', 'application/pdf');

        doc.pipe(res);

        // Header
        doc.fontSize(25).text(property.title, { align: 'center' });
        doc.moveDown();
        doc.fontSize(16).text(`Location: ${property.location}`, { align: 'center' });
        doc.fontSize(16).text(`Price: ${property.price}`, { align: 'center' });
        doc.moveDown();

        // Image (Naive implementation: handle external URLs)
        // For local files, we'd use path.join. For external (Unsplash/Pexels), we need to fetch them.
        // Doing strictly text/specs for now to avoid async image fetching complexity in this quick implementation,
        // or just use a placeholder if available locally.

        doc.rect(50, 150, 500, 2).fill('#6D28D9'); // Divider
        doc.moveDown(2);

        // Specs
        doc.fillColor('black').fontSize(14).text("Property Details:", { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).text(`Type: ${property.type}`);
        doc.text(`Bedrooms: ${property.bedrooms}`);
        doc.text(`Bathrooms: ${property.bathrooms}`);
        doc.text(`Area: ${property.area || property.areaSize} sqft`);
        doc.text(`Tenure: ${property.tenure || 'Freehold'}`);

        doc.moveDown();
        doc.fontSize(14).text("Description:", { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10).text(property.description || "No description provided.");

        doc.moveDown(2);
        doc.fontSize(14).text("Agent Contact:", { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).text(`Name: ${property.agentName || "ZynoxBit Agent"}`);
        doc.text(`Contact: ${property.agentContact || "+60 12-345 6789"}`);

        // Footer
        doc.moveDown(4);
        doc.fontSize(10).fillColor('gray').text("Generated by ZynoxBit Property Portal", { align: 'center' });

        doc.end();

    } catch (error) {
        console.error("PDF Generation Error:", error);
        res.status(500).json({ message: "Failed to generate PDF" });
    }
};
